### ISSUE TITLE
Hi, I am trying to run the repo and I keep getting this error, any help would be appreciated. Thanks!

### ISSUE THREAD

**Issue by McHarold404** [luka-group/Lattice#7]
Traceback (most recent call last):
  File "train.py", line 569, in <module>
    main()
  File "train.py", line 503, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/subtlbot/.local/lib/python3.8/site-packages/transformers/trainer.py", line 1316, in train
    tr_loss_step = self.training_step(model, inputs)
  File "/home/subtlbot/.local/lib/python3.8/site-packages/transformers/trainer.py", line 1849, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/subtlbot/.local/lib/python3.8/site-packages/transformers/trainer.py", line 1881, in compute_loss
    outputs = model(**inputs)
  File "/home/subtlbot/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/subtlbot/ToTTo/Lattice/model/modeling_t5.py", line 1557, in forward
    encoder_outputs = self.encoder(
  File "/home/subtlbot/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/subtlbot/ToTTo/Lattice/model/modeling_t5.py", line 919, in forward
    inputs_embeds = self.embed_tokens(input_ids)
  File "/home/subtlbot/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/subtlbot/.local/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/home/subtlbot/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 2199, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)

**Comment by FeiWang96** [comment]
Hi. It said the model and inputs are on different devices (CPU and GPU). By default, the huggingface/transformers package will handle that given the CUDA_VISIBLE_DEVICES=xxx. Did you change anything?
